name: flutter_lottie_4basic
description: Use lottie in flutter to render animations for iOS and Android, support some basic features
version: 0.3.0
homepage: https://github.com/royguanyu/flutter_lottie_4basic

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tw.roy.flutter_lottie_4basic
        pluginClass: FlutterLottiePlugin
      ios:
        pluginClass: FlutterLottiePlugin