name: roy_flutter_lottie
description: Use lottie in flutter to render animations for iOS and Android
version: 0.2.6
homepage: https://github.com/royguanyu/flutter_lottie

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shotouch.roy.flutter_lottie
    pluginClass: FlutterLottiePlugin
