name: flutter_lottie_lotum
description: Use lottie in flutter to render animations for iOS and Android
version: 0.2.9
homepage: https://github.com/lotum/flutter_lottie_lotum

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shotouch.roy.flutter_lottie
    pluginClass: FlutterLottiePlugin
